# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61shboard_service.proto\x12\x12\x62lockjoy.api.ui_v1\x1a\x0c\x63ommon.proto\"D\n\x13\x44\x61shboardKpiRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\"o\n\x14\x44\x61shboardKpiResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\x12\'\n\x06values\x18\x02 \x03(\x0b\x32\x17.blockjoy.api.ui_v1.KPI2o\n\x10\x44\x61shboardService\x12[\n\x04KPIs\x12\'.blockjoy.api.ui_v1.DashboardKpiRequest\x1a(.blockjoy.api.ui_v1.DashboardKpiResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DASHBOARDKPIREQUEST._serialized_start=61
  _DASHBOARDKPIREQUEST._serialized_end=129
  _DASHBOARDKPIRESPONSE._serialized_start=131
  _DASHBOARDKPIRESPONSE._serialized_end=242
  _DASHBOARDSERVICE._serialized_start=244
  _DASHBOARDSERVICE._serialized_end=355
# @@protoc_insertion_point(module_scope)
