# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fe_host_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x65_host_service.proto\x12\x12\x62lockjoy.api.ui_v1\x1a\x0c\x63ommon.proto\"\xca\x01\n\x0fGetHostsRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12)\n\x02id\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.UuidH\x00\x88\x01\x01\x12-\n\x06org_id\x18\x03 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.UuidH\x01\x88\x01\x01\x12\x12\n\x05token\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x05\n\x03_idB\t\n\x07_org_idB\x08\n\x06_token\"k\n\x10GetHostsResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\x12\'\n\x05hosts\x18\x02 \x03(\x0b\x32\x18.blockjoy.api.ui_v1.Host\"j\n\x11\x43reateHostRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12&\n\x04host\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.Host\"D\n\x12\x43reateHostResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\"j\n\x11UpdateHostRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12&\n\x04host\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.Host\"D\n\x12UpdateHostResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\"h\n\x11\x44\x65leteHostRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12$\n\x02id\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.Uuid\"D\n\x12\x44\x65leteHostResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta2\xf2\x02\n\x0bHostService\x12R\n\x03Get\x12#.blockjoy.api.ui_v1.GetHostsRequest\x1a$.blockjoy.api.ui_v1.GetHostsResponse\"\x00\x12Y\n\x06\x43reate\x12%.blockjoy.api.ui_v1.CreateHostRequest\x1a&.blockjoy.api.ui_v1.CreateHostResponse\"\x00\x12Y\n\x06Update\x12%.blockjoy.api.ui_v1.UpdateHostRequest\x1a&.blockjoy.api.ui_v1.UpdateHostResponse\"\x00\x12Y\n\x06\x44\x65lete\x12%.blockjoy.api.ui_v1.DeleteHostRequest\x1a&.blockjoy.api.ui_v1.DeleteHostResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fe_host_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETHOSTSREQUEST._serialized_start=60
  _GETHOSTSREQUEST._serialized_end=262
  _GETHOSTSRESPONSE._serialized_start=264
  _GETHOSTSRESPONSE._serialized_end=371
  _CREATEHOSTREQUEST._serialized_start=373
  _CREATEHOSTREQUEST._serialized_end=479
  _CREATEHOSTRESPONSE._serialized_start=481
  _CREATEHOSTRESPONSE._serialized_end=549
  _UPDATEHOSTREQUEST._serialized_start=551
  _UPDATEHOSTREQUEST._serialized_end=657
  _UPDATEHOSTRESPONSE._serialized_start=659
  _UPDATEHOSTRESPONSE._serialized_end=727
  _DELETEHOSTREQUEST._serialized_start=729
  _DELETEHOSTREQUEST._serialized_end=833
  _DELETEHOSTRESPONSE._serialized_start=835
  _DELETEHOSTRESPONSE._serialized_end=903
  _HOSTSERVICE._serialized_start=906
  _HOSTSERVICE._serialized_end=1276
# @@protoc_insertion_point(module_scope)
