# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: host_provision_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1chost_provision_service.proto\x12\x12\x62lockjoy.api.ui_v1\x1a\x0c\x63ommon.proto\"n\n\x17GetHostProvisionRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12$\n\x02id\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.Uuid\"\x85\x01\n\x18GetHostProvisionResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\x12\x39\n\x0ehost_provision\x18\x02 \x01(\x0b\x32!.blockjoy.api.ui_v1.HostProvision\"\x86\x01\n\x1a\x43reateHostProvisionRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12\x39\n\x0ehost_provision\x18\x02 \x01(\x0b\x32!.blockjoy.api.ui_v1.HostProvision\"M\n\x1b\x43reateHostProvisionResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta2\xe7\x01\n\x14HostProvisionService\x12\x62\n\x03Get\x12+.blockjoy.api.ui_v1.GetHostProvisionRequest\x1a,.blockjoy.api.ui_v1.GetHostProvisionResponse\"\x00\x12k\n\x06\x43reate\x12..blockjoy.api.ui_v1.CreateHostProvisionRequest\x1a/.blockjoy.api.ui_v1.CreateHostProvisionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'host_provision_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETHOSTPROVISIONREQUEST._serialized_start=66
  _GETHOSTPROVISIONREQUEST._serialized_end=176
  _GETHOSTPROVISIONRESPONSE._serialized_start=179
  _GETHOSTPROVISIONRESPONSE._serialized_end=312
  _CREATEHOSTPROVISIONREQUEST._serialized_start=315
  _CREATEHOSTPROVISIONREQUEST._serialized_end=449
  _CREATEHOSTPROVISIONRESPONSE._serialized_start=451
  _CREATEHOSTPROVISIONRESPONSE._serialized_end=528
  _HOSTPROVISIONSERVICE._serialized_start=531
  _HOSTPROVISIONSERVICE._serialized_end=762
# @@protoc_insertion_point(module_scope)
