# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aorganization_service.proto\x12\x12\x62lockjoy.api.ui_v1\x1a\x0c\x63ommon.proto\"H\n\x17GetOrganizationsRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\"\x83\x01\n\x18GetOrganizationsResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\x12\x37\n\rorganizations\x18\x02 \x03(\x0b\x32 .blockjoy.api.ui_v1.Organization\"\x82\x01\n\x19\x43reateOrganizationRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12\x36\n\x0corganization\x18\x02 \x01(\x0b\x32 .blockjoy.api.ui_v1.Organization\"L\n\x1a\x43reateOrganizationResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\"\x82\x01\n\x19UpdateOrganizationRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12\x36\n\x0corganization\x18\x02 \x01(\x0b\x32 .blockjoy.api.ui_v1.Organization\"L\n\x1aUpdateOrganizationResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\"p\n\x19\x44\x65leteOrganizationRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\x12$\n\x02id\x18\x02 \x01(\x0b\x32\x18.blockjoy.api.ui_v1.Uuid\"L\n\x1a\x44\x65leteOrganizationResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta2\xba\x03\n\x13OrganizationService\x12\x62\n\x03Get\x12+.blockjoy.api.ui_v1.GetOrganizationsRequest\x1a,.blockjoy.api.ui_v1.GetOrganizationsResponse\"\x00\x12i\n\x06\x43reate\x12-.blockjoy.api.ui_v1.CreateOrganizationRequest\x1a..blockjoy.api.ui_v1.CreateOrganizationResponse\"\x00\x12i\n\x06Update\x12-.blockjoy.api.ui_v1.UpdateOrganizationRequest\x1a..blockjoy.api.ui_v1.UpdateOrganizationResponse\"\x00\x12i\n\x06\x44\x65lete\x12-.blockjoy.api.ui_v1.DeleteOrganizationRequest\x1a..blockjoy.api.ui_v1.DeleteOrganizationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'organization_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETORGANIZATIONSREQUEST._serialized_start=64
  _GETORGANIZATIONSREQUEST._serialized_end=136
  _GETORGANIZATIONSRESPONSE._serialized_start=139
  _GETORGANIZATIONSRESPONSE._serialized_end=270
  _CREATEORGANIZATIONREQUEST._serialized_start=273
  _CREATEORGANIZATIONREQUEST._serialized_end=403
  _CREATEORGANIZATIONRESPONSE._serialized_start=405
  _CREATEORGANIZATIONRESPONSE._serialized_end=481
  _UPDATEORGANIZATIONREQUEST._serialized_start=484
  _UPDATEORGANIZATIONREQUEST._serialized_end=614
  _UPDATEORGANIZATIONRESPONSE._serialized_start=616
  _UPDATEORGANIZATIONRESPONSE._serialized_end=692
  _DELETEORGANIZATIONREQUEST._serialized_start=694
  _DELETEORGANIZATIONREQUEST._serialized_end=806
  _DELETEORGANIZATIONRESPONSE._serialized_start=808
  _DELETEORGANIZATIONRESPONSE._serialized_end=884
  _ORGANIZATIONSERVICE._serialized_start=887
  _ORGANIZATIONSERVICE._serialized_end=1329
# @@protoc_insertion_point(module_scope)
