# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14update_service.proto\x12\x12\x62lockjoy.api.ui_v1\x1a\x0c\x63ommon.proto\"B\n\x11GetUpdatesRequest\x12-\n\x04meta\x18\x01 \x01(\x0b\x32\x1f.blockjoy.api.ui_v1.RequestMeta\"t\n\x12GetUpdatesResponse\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .blockjoy.api.ui_v1.ResponseMeta\x12.\n\x06update\x18\x02 \x01(\x0b\x32\x1e.blockjoy.api.ui_v1.InfoUpdate2m\n\rUpdateService\x12\\\n\x07Updates\x12%.blockjoy.api.ui_v1.GetUpdatesRequest\x1a&.blockjoy.api.ui_v1.GetUpdatesResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUPDATESREQUEST._serialized_start=58
  _GETUPDATESREQUEST._serialized_end=124
  _GETUPDATESRESPONSE._serialized_start=126
  _GETUPDATESRESPONSE._serialized_end=242
  _UPDATESERVICE._serialized_start=244
  _UPDATESERVICE._serialized_end=353
# @@protoc_insertion_point(module_scope)
