// source: host_provision_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.blockjoy.api.ui_v1.CreateHostProvisionRequest', null, global);
goog.exportSymbol('proto.blockjoy.api.ui_v1.CreateHostProvisionResponse', null, global);
goog.exportSymbol('proto.blockjoy.api.ui_v1.GetHostProvisionRequest', null, global);
goog.exportSymbol('proto.blockjoy.api.ui_v1.GetHostProvisionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.blockjoy.api.ui_v1.GetHostProvisionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.blockjoy.api.ui_v1.GetHostProvisionRequest.displayName = 'proto.blockjoy.api.ui_v1.GetHostProvisionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.blockjoy.api.ui_v1.GetHostProvisionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.blockjoy.api.ui_v1.GetHostProvisionResponse.displayName = 'proto.blockjoy.api.ui_v1.GetHostProvisionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.blockjoy.api.ui_v1.CreateHostProvisionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.displayName = 'proto.blockjoy.api.ui_v1.CreateHostProvisionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.blockjoy.api.ui_v1.CreateHostProvisionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.displayName = 'proto.blockjoy.api.ui_v1.CreateHostProvisionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.blockjoy.api.ui_v1.GetHostProvisionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && common_pb.RequestMeta.toObject(includeInstance, f),
    id: (f = msg.getId()) && common_pb.Uuid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.blockjoy.api.ui_v1.GetHostProvisionRequest;
  return proto.blockjoy.api.ui_v1.GetHostProvisionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.RequestMeta;
      reader.readMessage(value,common_pb.RequestMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 2:
      var value = new common_pb.Uuid;
      reader.readMessage(value,common_pb.Uuid.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.blockjoy.api.ui_v1.GetHostProvisionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.RequestMeta.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.Uuid.serializeBinaryToWriter
    );
  }
};


/**
 * optional RequestMeta meta = 1;
 * @return {?proto.blockjoy.api.ui_v1.RequestMeta}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.getMeta = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.RequestMeta} */ (
    jspb.Message.getWrapperField(this, common_pb.RequestMeta, 1));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.RequestMeta|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} returns this
*/
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} returns this
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Uuid id = 2;
 * @return {?proto.blockjoy.api.ui_v1.Uuid}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.getId = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.Uuid} */ (
    jspb.Message.getWrapperField(this, common_pb.Uuid, 2));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.Uuid|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} returns this
*/
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionRequest} returns this
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.blockjoy.api.ui_v1.GetHostProvisionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && common_pb.ResponseMeta.toObject(includeInstance, f),
    hostProvision: (f = msg.getHostProvision()) && common_pb.HostProvision.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.blockjoy.api.ui_v1.GetHostProvisionResponse;
  return proto.blockjoy.api.ui_v1.GetHostProvisionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ResponseMeta;
      reader.readMessage(value,common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 2:
      var value = new common_pb.HostProvision;
      reader.readMessage(value,common_pb.HostProvision.deserializeBinaryFromReader);
      msg.setHostProvision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.blockjoy.api.ui_v1.GetHostProvisionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
  f = message.getHostProvision();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.HostProvision.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseMeta meta = 1;
 * @return {?proto.blockjoy.api.ui_v1.ResponseMeta}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.getMeta = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, common_pb.ResponseMeta, 1));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.ResponseMeta|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} returns this
*/
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} returns this
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HostProvision host_provision = 2;
 * @return {?proto.blockjoy.api.ui_v1.HostProvision}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.getHostProvision = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.HostProvision} */ (
    jspb.Message.getWrapperField(this, common_pb.HostProvision, 2));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.HostProvision|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} returns this
*/
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.setHostProvision = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.GetHostProvisionResponse} returns this
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.clearHostProvision = function() {
  return this.setHostProvision(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.GetHostProvisionResponse.prototype.hasHostProvision = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && common_pb.RequestMeta.toObject(includeInstance, f),
    hostProvision: (f = msg.getHostProvision()) && common_pb.HostProvision.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.blockjoy.api.ui_v1.CreateHostProvisionRequest;
  return proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.RequestMeta;
      reader.readMessage(value,common_pb.RequestMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 2:
      var value = new common_pb.HostProvision;
      reader.readMessage(value,common_pb.HostProvision.deserializeBinaryFromReader);
      msg.setHostProvision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.RequestMeta.serializeBinaryToWriter
    );
  }
  f = message.getHostProvision();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.HostProvision.serializeBinaryToWriter
    );
  }
};


/**
 * optional RequestMeta meta = 1;
 * @return {?proto.blockjoy.api.ui_v1.RequestMeta}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.getMeta = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.RequestMeta} */ (
    jspb.Message.getWrapperField(this, common_pb.RequestMeta, 1));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.RequestMeta|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} returns this
*/
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} returns this
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HostProvision host_provision = 2;
 * @return {?proto.blockjoy.api.ui_v1.HostProvision}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.getHostProvision = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.HostProvision} */ (
    jspb.Message.getWrapperField(this, common_pb.HostProvision, 2));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.HostProvision|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} returns this
*/
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.setHostProvision = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionRequest} returns this
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.clearHostProvision = function() {
  return this.setHostProvision(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionRequest.prototype.hasHostProvision = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.blockjoy.api.ui_v1.CreateHostProvisionResponse;
  return proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ResponseMeta;
      reader.readMessage(value,common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseMeta meta = 1;
 * @return {?proto.blockjoy.api.ui_v1.ResponseMeta}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.getMeta = function() {
  return /** @type{?proto.blockjoy.api.ui_v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, common_pb.ResponseMeta, 1));
};


/**
 * @param {?proto.blockjoy.api.ui_v1.ResponseMeta|undefined} value
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse} returns this
*/
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.blockjoy.api.ui_v1.CreateHostProvisionResponse} returns this
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.blockjoy.api.ui_v1.CreateHostProvisionResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.blockjoy.api.ui_v1);
