# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: billing_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'billing_service_pb'

module Blockjoy
  module Api
    module UiV1
      module BillingService
        # Billing related services 
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.BillingService'

          rpc :Create, ::Blockjoy::Api::UiV1::CreateBillRequest, ::Blockjoy::Api::UiV1::CreateBillResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
