# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billing_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("billing_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.CreateBillRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      proto3_optional :user_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :org_id, :message, 3, "blockjoy.api.ui_v1.Uuid"
    end
    add_message "blockjoy.api.ui_v1.CreateBillResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      optional :bill, :message, 2, "blockjoy.api.ui_v1.Bill"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      CreateBillRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateBillRequest").msgclass
      CreateBillResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateBillResponse").msgclass
    end
  end
end
