# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/any_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.Uuid" do
      optional :value, :string, 1
    end
    add_message "blockjoy.api.ui_v1.ApiToken" do
      optional :value, :string, 1
    end
    add_message "blockjoy.api.ui_v1.Pagination" do
      optional :total_items, :int32, 1
      optional :offset, :int32, 2
      optional :items_per_page, :int32, 3
    end
    add_message "blockjoy.api.ui_v1.RequestMeta" do
      optional :id, :message, 1, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :token, :message, 2, "blockjoy.api.ui_v1.ApiToken"
      repeated :fields, :string, 3
      proto3_optional :limit, :int32, 4
    end
    add_message "blockjoy.api.ui_v1.ResponseMeta" do
      optional :status, :enum, 1, "blockjoy.api.ui_v1.ResponseMeta.Status"
      optional :origin_request_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      repeated :messages, :string, 3
      proto3_optional :pagination, :message, 4, "blockjoy.api.ui_v1.Pagination"
    end
    add_enum "blockjoy.api.ui_v1.ResponseMeta.Status" do
      value :UnknownResponse, 0
      value :Success, 1
      value :GeneralError, 2
    end
    add_message "blockjoy.api.ui_v1.Host" do
      proto3_optional :id, :message, 1, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :org_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :name, :string, 3
      proto3_optional :version, :string, 4
      proto3_optional :location, :string, 5
      proto3_optional :cpu_count, :int64, 6
      proto3_optional :mem_size, :int64, 7
      proto3_optional :disk_size, :int64, 8
      proto3_optional :os, :string, 9
      proto3_optional :os_version, :string, 10
      proto3_optional :ip, :string, 11
      proto3_optional :status, :enum, 12, "blockjoy.api.ui_v1.Host.HostStatus"
      repeated :nodes, :message, 13, "blockjoy.api.ui_v1.Node"
      proto3_optional :created_at, :message, 14, "google.protobuf.Timestamp"
    end
    add_enum "blockjoy.api.ui_v1.Host.HostStatus" do
      value :UndefinedContainerStatus, 0
      value :Creating, 1
      value :Running, 2
      value :Starting, 3
      value :Stopping, 4
      value :Stopped, 5
      value :Upgrading, 6
      value :Upgraded, 7
      value :Deleting, 8
      value :Deleted, 9
      value :Installing, 10
      value :Snapshotting, 11
    end
    add_message "blockjoy.api.ui_v1.HostProvision" do
      proto3_optional :id, :string, 1
      proto3_optional :org_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :host_id, :message, 3, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :created_at, :message, 4, "google.protobuf.Timestamp"
      proto3_optional :claimed_at, :message, 5, "google.protobuf.Timestamp"
      proto3_optional :install_cmd, :string, 6
    end
    add_message "blockjoy.api.ui_v1.Node" do
      proto3_optional :id, :message, 1, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :org_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :blockchain_id, :message, 3, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :name, :string, 4
      repeated :groups, :string, 5
      proto3_optional :version, :string, 6
      proto3_optional :ip, :string, 7
      proto3_optional :type, :enum, 8, "blockjoy.api.ui_v1.Node.NodeType"
      proto3_optional :address, :string, 9
      proto3_optional :wallet_address, :string, 10
      proto3_optional :block_height, :int64, 11
      proto3_optional :node_data, :bytes, 12
      proto3_optional :created_at, :message, 13, "google.protobuf.Timestamp"
      proto3_optional :updated_at, :message, 14, "google.protobuf.Timestamp"
      proto3_optional :status, :enum, 15, "blockjoy.api.ui_v1.Node.NodeStatus"
    end
    add_enum "blockjoy.api.ui_v1.Node.NodeType" do
      value :UndefinedType, 0
      value :Node, 1
      value :API, 2
      value :ETL, 3
      value :Miner, 4
      value :Validator, 5
      value :Oracle, 6
      value :Relay, 7
    end
    add_enum "blockjoy.api.ui_v1.Node.NodeStatus" do
      value :UndefinedApplicationStatus, 0
      value :Broadcasting, 1
      value :Cancelled, 2
      value :Delegating, 3
      value :Delinquent, 4
      value :Disabled, 5
      value :Earning, 6
      value :Electing, 7
      value :Elected, 8
      value :Exporting, 9
      value :Ingesting, 10
      value :Mining, 11
      value :Minting, 12
      value :Processing, 13
      value :Relaying, 14
      value :Removed, 15
      value :Removing, 16
    end
    add_message "blockjoy.api.ui_v1.Organization" do
      proto3_optional :id, :message, 1, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :name, :string, 2
      proto3_optional :personal, :bool, 3
      proto3_optional :member_count, :int64, 4
      proto3_optional :created_at, :message, 13, "google.protobuf.Timestamp"
      proto3_optional :updated_at, :message, 14, "google.protobuf.Timestamp"
    end
    add_message "blockjoy.api.ui_v1.InfoUpdate" do
      proto3_optional :host, :message, 1, "blockjoy.api.ui_v1.Host"
      proto3_optional :node, :message, 2, "blockjoy.api.ui_v1.Node"
    end
    add_message "blockjoy.api.ui_v1.User" do
      proto3_optional :id, :message, 1, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :email, :string, 2
      proto3_optional :first_name, :string, 3
      proto3_optional :last_name, :string, 4
      proto3_optional :created_at, :message, 5, "google.protobuf.Timestamp"
      proto3_optional :updated_at, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "blockjoy.api.ui_v1.Bill" do
      proto3_optional :id, :string, 1
      proto3_optional :created_at, :message, 2, "google.protobuf.Timestamp"
      proto3_optional :tax_number, :string, 3
      proto3_optional :receiver_name, :string, 4
      proto3_optional :receiver_address, :string, 5
      proto3_optional :tax_rate, :float, 6
      proto3_optional :net_amount, :float, 7
      proto3_optional :gross_amount, :float, 8
      proto3_optional :pdf_url, :string, 9
    end
    add_message "blockjoy.api.ui_v1.KPI" do
      optional :name, :enum, 1, "blockjoy.api.ui_v1.KPI.Name"
      optional :value, :message, 2, "google.protobuf.Any"
    end
    add_enum "blockjoy.api.ui_v1.KPI.Name" do
      value :Unknown, 0
      value :Nodes, 1
      value :Hosts, 2
      value :Online, 3
      value :Offline, 4
    end
    add_message "blockjoy.api.ui_v1.UserConfigurationParameter" do
      optional :name, :string, 1
      optional :value, :message, 2, "google.protobuf.Any"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      Uuid = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Uuid").msgclass
      ApiToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.ApiToken").msgclass
      Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Pagination").msgclass
      RequestMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.RequestMeta").msgclass
      ResponseMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.ResponseMeta").msgclass
      ResponseMeta::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.ResponseMeta.Status").enummodule
      Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Host").msgclass
      Host::HostStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Host.HostStatus").enummodule
      HostProvision = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.HostProvision").msgclass
      Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Node").msgclass
      Node::NodeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Node.NodeType").enummodule
      Node::NodeStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Node.NodeStatus").enummodule
      Organization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Organization").msgclass
      InfoUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.InfoUpdate").msgclass
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.User").msgclass
      Bill = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.Bill").msgclass
      KPI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.KPI").msgclass
      KPI::Name = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.KPI.Name").enummodule
      UserConfigurationParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UserConfigurationParameter").msgclass
    end
  end
end
