# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dashboard_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.DashboardKpiRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
    end
    add_message "blockjoy.api.ui_v1.DashboardKpiResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      repeated :values, :message, 2, "blockjoy.api.ui_v1.KPI"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      DashboardKpiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DashboardKpiRequest").msgclass
      DashboardKpiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DashboardKpiResponse").msgclass
    end
  end
end
