# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fe_host_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fe_host_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.GetHostsRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      proto3_optional :id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :org_id, :message, 3, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :token, :string, 4
    end
    add_message "blockjoy.api.ui_v1.GetHostsResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      repeated :hosts, :message, 2, "blockjoy.api.ui_v1.Host"
    end
    add_message "blockjoy.api.ui_v1.CreateHostRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :host, :message, 2, "blockjoy.api.ui_v1.Host"
    end
    add_message "blockjoy.api.ui_v1.CreateHostResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.UpdateHostRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :host, :message, 2, "blockjoy.api.ui_v1.Host"
    end
    add_message "blockjoy.api.ui_v1.UpdateHostResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.DeleteHostRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :id, :message, 2, "blockjoy.api.ui_v1.Uuid"
    end
    add_message "blockjoy.api.ui_v1.DeleteHostResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      GetHostsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetHostsRequest").msgclass
      GetHostsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetHostsResponse").msgclass
      CreateHostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateHostRequest").msgclass
      CreateHostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateHostResponse").msgclass
      UpdateHostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateHostRequest").msgclass
      UpdateHostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateHostResponse").msgclass
      DeleteHostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DeleteHostRequest").msgclass
      DeleteHostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DeleteHostResponse").msgclass
    end
  end
end
