# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: host_provision_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'host_provision_service_pb'

module Blockjoy
  module Api
    module UiV1
      module HostProvisionService
        # Host provisioning 
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.HostProvisionService'

          # Get a single host provision 
          rpc :Get, ::Blockjoy::Api::UiV1::GetHostProvisionRequest, ::Blockjoy::Api::UiV1::GetHostProvisionResponse
          # Create a single host provision 
          rpc :Create, ::Blockjoy::Api::UiV1::CreateHostProvisionRequest, ::Blockjoy::Api::UiV1::CreateHostProvisionResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
