# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("node_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.CreateNodeRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :node, :message, 2, "blockjoy.api.ui_v1.Node"
    end
    add_message "blockjoy.api.ui_v1.CreateNodeResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.GetNodeRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      proto3_optional :id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      proto3_optional :org_id, :message, 3, "blockjoy.api.ui_v1.Uuid"
    end
    add_message "blockjoy.api.ui_v1.GetNodeResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      repeated :nodes, :message, 2, "blockjoy.api.ui_v1.Node"
    end
    add_message "blockjoy.api.ui_v1.UpdateNodeRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :node, :message, 2, "blockjoy.api.ui_v1.Node"
    end
    add_message "blockjoy.api.ui_v1.UpdateNodeResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      CreateNodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateNodeRequest").msgclass
      CreateNodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateNodeResponse").msgclass
      GetNodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetNodeRequest").msgclass
      GetNodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetNodeResponse").msgclass
      UpdateNodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateNodeRequest").msgclass
      UpdateNodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateNodeResponse").msgclass
    end
  end
end
