# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: node_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'node_service_pb'

module Blockjoy
  module Api
    module UiV1
      module NodeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.NodeService'

          # Get blockchain node(s) 
          rpc :Get, ::Blockjoy::Api::UiV1::GetNodeRequest, ::Blockjoy::Api::UiV1::GetNodeResponse
          # Create a single blockchain node 
          rpc :Create, ::Blockjoy::Api::UiV1::CreateNodeRequest, ::Blockjoy::Api::UiV1::CreateNodeResponse
          # Update a single blockchain node 
          rpc :Update, ::Blockjoy::Api::UiV1::UpdateNodeRequest, ::Blockjoy::Api::UiV1::UpdateNodeResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
