# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("organization_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.GetOrganizationsRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
    end
    add_message "blockjoy.api.ui_v1.GetOrganizationsResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      repeated :organizations, :message, 2, "blockjoy.api.ui_v1.Organization"
    end
    add_message "blockjoy.api.ui_v1.CreateOrganizationRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :organization, :message, 2, "blockjoy.api.ui_v1.Organization"
    end
    add_message "blockjoy.api.ui_v1.CreateOrganizationResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.UpdateOrganizationRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :organization, :message, 2, "blockjoy.api.ui_v1.Organization"
    end
    add_message "blockjoy.api.ui_v1.UpdateOrganizationResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.DeleteOrganizationRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :id, :message, 2, "blockjoy.api.ui_v1.Uuid"
    end
    add_message "blockjoy.api.ui_v1.DeleteOrganizationResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      GetOrganizationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetOrganizationsRequest").msgclass
      GetOrganizationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetOrganizationsResponse").msgclass
      CreateOrganizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateOrganizationRequest").msgclass
      CreateOrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateOrganizationResponse").msgclass
      UpdateOrganizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateOrganizationRequest").msgclass
      UpdateOrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpdateOrganizationResponse").msgclass
      DeleteOrganizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DeleteOrganizationRequest").msgclass
      DeleteOrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.DeleteOrganizationResponse").msgclass
    end
  end
end
