# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: organization_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'organization_service_pb'

module Blockjoy
  module Api
    module UiV1
      module OrganizationService
        # Manage organizations 
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.OrganizationService'

          # Get all the organizations for a user. All users automatically get a private (internal) organization 
          rpc :Get, ::Blockjoy::Api::UiV1::GetOrganizationsRequest, ::Blockjoy::Api::UiV1::GetOrganizationsResponse
          # Create a single organization 
          rpc :Create, ::Blockjoy::Api::UiV1::CreateOrganizationRequest, ::Blockjoy::Api::UiV1::CreateOrganizationResponse
          # Update a single organization 
          rpc :Update, ::Blockjoy::Api::UiV1::UpdateOrganizationRequest, ::Blockjoy::Api::UiV1::UpdateOrganizationResponse
          # Delete a single organization 
          rpc :Delete, ::Blockjoy::Api::UiV1::DeleteOrganizationRequest, ::Blockjoy::Api::UiV1::DeleteOrganizationResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
