# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("update_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.GetUpdatesRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
    end
    add_message "blockjoy.api.ui_v1.GetUpdatesResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      optional :update, :message, 2, "blockjoy.api.ui_v1.InfoUpdate"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      GetUpdatesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetUpdatesRequest").msgclass
      GetUpdatesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetUpdatesResponse").msgclass
    end
  end
end
