# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: update_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'update_service_pb'

module Blockjoy
  module Api
    module UiV1
      module UpdateService
        # Retrieve updates sent by the API server 
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.UpdateService'

          # Open a persisted connection to receive updates on entities as they occur on the server side 
          rpc :Updates, ::Blockjoy::Api::UiV1::GetUpdatesRequest, stream(::Blockjoy::Api::UiV1::GetUpdatesResponse)
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
