# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'blockjoy.api.ui_v1'

require 'grpc'
require 'user_service_pb'

module Blockjoy
  module Api
    module UiV1
      module UserService
        # User related services 
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'blockjoy.api.ui_v1.UserService'

          # Retrieve a single user 
          rpc :Get, ::Blockjoy::Api::UiV1::GetUserRequest, ::Blockjoy::Api::UiV1::GetUserResponse
          # Create a single user 
          rpc :Create, ::Blockjoy::Api::UiV1::CreateUserRequest, ::Blockjoy::Api::UiV1::CreateUserResponse
          # Create/update configuration parameters 
          rpc :UpsertConfiguration, ::Blockjoy::Api::UiV1::UpsertConfigurationRequest, ::Blockjoy::Api::UiV1::UpsertConfigurationResponse
          # Retrieve all configuration parameters 
          rpc :GetConfiguration, ::Blockjoy::Api::UiV1::GetConfigurationRequest, ::Blockjoy::Api::UiV1::GetConfigurationResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
