# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

require 'google/protobuf'

require 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_service.proto", :syntax => :proto3) do
    add_message "blockjoy.api.ui_v1.GetUserRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
    end
    add_message "blockjoy.api.ui_v1.GetUserResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      optional :user, :message, 2, "blockjoy.api.ui_v1.User"
    end
    add_message "blockjoy.api.ui_v1.CreateUserRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :user, :message, 2, "blockjoy.api.ui_v1.User"
      optional :password, :string, 3
      optional :password_confirmation, :string, 4
    end
    add_message "blockjoy.api.ui_v1.CreateUserResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.UpsertConfigurationRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :user_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
      repeated :params, :message, 3, "blockjoy.api.ui_v1.UserConfigurationParameter"
    end
    add_message "blockjoy.api.ui_v1.UpsertConfigurationResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
    end
    add_message "blockjoy.api.ui_v1.GetConfigurationRequest" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.RequestMeta"
      optional :user_id, :message, 2, "blockjoy.api.ui_v1.Uuid"
    end
    add_message "blockjoy.api.ui_v1.GetConfigurationResponse" do
      optional :meta, :message, 1, "blockjoy.api.ui_v1.ResponseMeta"
      repeated :params, :message, 2, "blockjoy.api.ui_v1.UserConfigurationParameter"
    end
  end
end

module Blockjoy
  module Api
    module UiV1
      GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetUserRequest").msgclass
      GetUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetUserResponse").msgclass
      CreateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateUserRequest").msgclass
      CreateUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.CreateUserResponse").msgclass
      UpsertConfigurationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpsertConfigurationRequest").msgclass
      UpsertConfigurationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.UpsertConfigurationResponse").msgclass
      GetConfigurationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetConfigurationRequest").msgclass
      GetConfigurationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blockjoy.api.ui_v1.GetConfigurationResponse").msgclass
    end
  end
end
